# 配置文件

DAILY_TIME: "16:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-08-04" # 纪念日
CITY: "香港"

BIRTHDAY:
  - "05-22"
  - "04-25"

APP_ID: "wx20eaec009aa07aad"
APP_SECRET: "e876b3e1f0a60576132f7c088944b5b8"

USER_ID: 
  - "oGOUE6f6_BsgrHTT-ATp5c0WJTYA	"
#   - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "vNR7wM6iuktPZ8p0dfVhf_ImYxEvUw6UCB0IUR09JSw"
